name: Update Data

on:
  schedule:
    # * Runs at 4AM Everyday
    - cron: 0 21 * * *

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/run.yml

jobs:
  updarte:
    name: Update Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Turborepo Magic
        run: GH_PAT=${{ secrets.GH_PAT }} pnpm turbo run analyze --filter="@leomotors/language-stats"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "[SKIP BUILD] Update Language Stats Data"
          default_author: github_actions
